/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.palerique.influenceanalysis;

public class Lambda {

    public static void main(String[] args) {
        System.out.println(new Lambda().getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
