/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.palerique.influenceanalysis.lambda;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
