/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.palerique.influenceanalysis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Lambda classUnderTest = new Lambda();
        assertNotNull(classUnderTest.getGreeting(), "lambda should have a greeting");
    }
}
