/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.palerique.influenceanalysis.layer;

import java.util.List;

public class StringUtils {

    public static String join(List<String> source) {
        return JoinUtils.join(source);
    }

    public static List<String> split(String source) {
        return SplitUtils.split(source);
    }
}
